#!/usr/bin/env python3
"""Plot Fig. 3d from the tables generated by ``calculate.py``."""

from __future__ import annotations

import argparse
from pathlib import Path

import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns


METHOD_COLORS = {"GRAVITY": "#7C9895", "CellDancer": "#92A5D1"}
LABELS = ("Cooperative", "Neutral", "Destabilizing")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--input-dir", type=Path, default=Path("outputs"))
    parser.add_argument("--output", type=Path, default=Path("outputs/fig3d.png"))
    args = parser.parse_args()

    summary = pd.read_csv(args.input_dir / "fig3d_summary.csv").set_index("method")
    figure = plt.figure(figsize=(10, 6), dpi=300)
    grid = figure.add_gridspec(2, 2, height_ratios=(0.6, 1.4), width_ratios=(1, 1), hspace=0.52, wspace=0.38)

    agreement_axis = figure.add_subplot(grid[0, 0])
    agreement = summary.loc[["GRAVITY", "CellDancer"], "label_agreement_count"]
    agreement_bars = agreement_axis.barh(agreement.index, agreement.values, color=[METHOD_COLORS[method] for method in agreement.index])
    for bar, value in zip(agreement_bars, agreement.values):
        agreement_axis.text(value + 0.8, bar.get_y() + bar.get_height() / 2, f"{value:d}", va="center", fontsize=10)
    agreement_axis.set_title("Label Agreement", fontsize=13)
    agreement_axis.set_xlabel("Correct Count", fontsize=10)
    agreement_axis.set_xlim(left=0)
    agreement_axis.invert_yaxis()
    agreement_axis.spines[["top", "right"]].set_visible(False)

    cosine_axis = figure.add_subplot(grid[0, 1])
    cosine = summary.loc[["GRAVITY", "CellDancer"], "cosine_spearman"]
    cosine_bars = cosine_axis.barh(cosine.index, cosine.values, color=[METHOD_COLORS[method] for method in cosine.index])
    for bar, value in zip(cosine_bars, cosine.values):
        if value >= 0:
            x_position, alignment, color = value + 0.008, "left", "black"
        else:
            x_position, alignment, color = value / 2, "center", "white"
        cosine_axis.text(x_position, bar.get_y() + bar.get_height() / 2, f"{value:.2f}", va="center", ha=alignment, color=color, fontsize=10)
    cosine_axis.axvline(0, color="black", linewidth=0.8)
    cosine_axis.set_title("Kappa & Gamma Cosine", fontsize=13)
    cosine_axis.set_xlabel("Spearman rho", fontsize=10)
    cosine_axis.invert_yaxis()
    cosine_axis.spines[["top", "right"]].set_visible(False)

    for axis, method in zip((figure.add_subplot(grid[1, 0]), figure.add_subplot(grid[1, 1])), ("GRAVITY", "CellDancer")):
        matrix = pd.read_csv(args.input_dir / f"{method.lower()}_label_confusion.csv", index_col=0).reindex(index=LABELS, columns=LABELS, fill_value=0)
        sns.heatmap(matrix, annot=True, fmt="d", cmap="GnBu", cbar=False, square=True, ax=axis, linewidths=0.5, linecolor="white")
        axis.set_title(method, fontsize=13)
        axis.set_xlabel("Predicted Label", fontsize=10)
        axis.set_ylabel("Real Label", fontsize=10)
        axis.tick_params(axis="x", rotation=0, labelsize=8)
        axis.tick_params(axis="y", rotation=0, labelsize=8)

    figure.subplots_adjust(left=0.08, right=0.98, bottom=0.08, top=0.94, wspace=0.38, hspace=0.52)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    figure.savefig(args.output, dpi=600, bbox_inches="tight")
    plt.close(figure)


if __name__ == "__main__":
    main()
